CREATE TABLE Game (
  id INT IDENTITY(1,1) PRIMARY KEY,
  userid VARCHAR(50) NOT NULL,
  number INT DEFAULT (ABS(CHECKSUM(NEWID()) % 10000)+1) NOT NULL,
  tries INT NOT NULL default 0,
  created_at DATETIME2 DEFAULT GETDATE() NOT NULL, 
  done_at DATETIME2 DEFAULT NULL,
);

ALTER TABLE Game ADD CONSTRAINT UQ_mytable UNIQUE (id, userid);
